CREATE TABLE BIOMETRIC (
	ID NUMBER NOT NULL CONSTRAINT BIOMETRIC_ID_PK PRIMARY KEY ,
	F1 VARCHAR2(50),
	F2 VARCHAR2(50),
	F3 VARCHAR2(50)
);
CREATE SEQUENCE BIOMETRIC_PK_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TB1 (
	ID NUMBER NOT NULL CONSTRAINT TB1_ID_PK PRIMARY KEY ,
	VALUE INT,
	REMARKS VARCHAR2(100)
);
CREATE SEQUENCE TB1_PK_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SUPPLIER(
	SUPPLIER_ID NUMBER(10) NOT NULL CONSTRAINT SUPPLIER_PK PRIMARY KEY,
	SUPPLIER_NAME VARCHAR2(50) NOT NULL ,
	CONTACT_NAME VARCHAR2(50)
)
CREATE SEQUENCE SUPPLIER_PK_SUPPLIER_ID_SEQ START WITH 1 INCREMENT BY 1;